name: CI Pipeline (Testing Branch)

on:
  push:
    branches:
      - testing

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Node.js for running tests (frontend/backend, etc.)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # Step 3: Install dependencies and run tests
    - name: Run tests for frontend
      run: |
        if [ -f ./frontend/package.json ]; then
          cd frontend
          npm install
          npm test || echo "No tests found in frontend"
          cd ..
        else
          echo "No frontend package.json found, skipping tests."
        fi

    - name: Run tests for backend
      run: |
        if [ -f ./backend/package.json ]; then
          cd backend
          npm install
          npm test || echo "No tests found in backend"
          cd ..
        else
          echo "No backend package.json found, skipping tests."
        fi

    # Step 4: Login to Azure using service principal
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 5: Login to ACR
    - name: Docker login to ACR
      run: |
        az acr login --name ${{ secrets.REGISTRY_NAME }}

    # Step 6: Build and Push Docker Images (only if tests passed)
    - name: Build & Push Docker Images
      run: |
        for service in frontend backend product order customer; do
          if [ -d "$service" ]; then
            IMAGE_NAME=${{ secrets.REGISTRY_LOGIN_SERVER }}/$service:${{ github.sha }}
            echo "Building and pushing image: $IMAGE_NAME"
            docker build -t $IMAGE_NAME ./$service
            docker push $IMAGE_NAME
          else
            echo "Directory $service not found, skipping."
          fi
        done.
